name: Run main.py every 15 minutes

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  run-main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run main.py
      run: python main.py ${{ secrets.API_KEY }}

    - name: Commit and push generated PDF
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global user.name 'advait-panicker'
          git config --global user.email 'advait-panicker@users.noreply.github.com'
          git add main.csv
          git commit -m "New data entry"
          git push
